services:
  backend:
    build: ./Backend
    container_name: scriblo-backend
    env_file:
      - ./Backend/.env
    expose:
      - "8000"

  frontend:
    build: ./Frontend
    container_name: scriblo-frontend
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    container_name: scriblo-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend